### ISSUE TITLE
M3 - Create Index quarto file and render to html (main page)

### ISSUE THREAD

**Issue by jfmartinez4** [ciesin-geospatial/TOPSTSCHOOL-disasters#2]
TO DO: Create a draft Quarto page to generate a main (index) page. 

Repo needs index page: https://github.com/ciesin-geospatial/TOPSTSCHOOL-disasters

Example of page: https://github.com/ciesin-geospatial/TOPSTSCHOOL-water/blob/main/index.qmd

Complete should look like a .qmd file with a placeholder information. Include information related to disasters instead of water. If lessons are missing, write "Lessons coming soon..."

**Comment by DavidFonsecaG** [comment]
@jfmartinez4 Thank you for adding. The index quarto file has been created. Only lesson 1 added. Other lessons coming soon...

I don't have write access to the repo, so a fork was created. Also a branch titled david_disasters-create-index was created. 

Changes were committed and pushed to my fork. Please let me know if there are any suggestions or changes needed.

**Comment by DavidFonsecaG** [comment]
I just realized that I did not include the link to the forked repo. Here it is: [https://github.com/DavidFonsecaG/TOPSTSCHOOL-disasters/blob/david_disasters-create-index/index.qmd](url).

**Comment by jfmartinez4** [comment]
@DavidFonsecaG Your updates should be in the form of a pull request. Please let me know if you are unsure on how to do that and I can send you some videos we have recorded.

**Comment by DavidFonsecaG** [comment]
Hi **@jfmartinez4**! I just created a pull request. Thank you

**Comment by jfmartinez4** [comment]
@DavidFonsecaG Thanks for the pull request, great job! 
Next step is to render an html page from the quarto document you added and create a new pull request. In the Python terminal you should need to write "quarto render index.qmd". Let me know if you have any questions.

**Comment by DavidFonsecaG** [comment]
Thanks, **@jfmartinez4**! I’ve already rendered the HTML from the **index.qmd** file using quarto render **index.qmd** and included it in the pull request. Let me know if there’s anything else you’d like me to tweak or add!
